---

- name: Reset the root password
  hosts: all
  vars_files:
    - root_password.yml
  tasks:
    - name: Reset password
      ansible.builtin.user:
        user: root
        state: present
        password: "{{ root_password | password_hash('sha512') }}"
